name: oxford_pet_lab
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow>=2.12.0
  - tensorflow-datasets>=4.9.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - opencv>=4.5.0
  - pillow>=8.0.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - tqdm>=4.62.0
  - pyyaml>=5.4.0
  - pip
  - pip:
    - albumentations>=1.3.0
    - wandb>=0.12.0
    - tensorboard>=2.7.0
    - plotly>=5.0.0
    - click>=8.0.0
    - colorama>=0.4.4
    - pytest>=6.2.0
    - pytest-cov>=2.12.0
    - torchmetrics>=0.11.0
    - timm>=0.6.0
    - segmentation-models>=1.0.1
    - tensorflow-addons>=0.21.0

